Different logging.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@50737 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/packages/open/deb/likewise-open.postinst b/build/packages/open/deb/likewise-open.postinst
--- a/build/packages/open/deb/likewise-open.postinst
+++ b/build/packages/open/deb/likewise-open.postinst
@@ -9,15 +9,38 @@ log()
     echo $1 >> $LOG
 }
 
-import_registry_configuration()
+exec_log()
 {
-    /opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg > $TLOG 2>&1
+    $1 > $TLOG
     err=$?
-    if [ $err -ne 0 ]; then
-        log "Error: /opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg returned $err"
+    if [ $err -eq 0 ]; then
+        echo $1 >> $LOG
+    else
+        log "Error: $1 returned $err"
         log `cat $TLOG`
+    fi
+    rm -f $TLOG > /dev/null 2> /dev/null
+}
+
+exec_log_exit()
+{
+    $1 > $TLOG
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo $1 >> $LOG
+    else
+        log "Error: $1 returned $err"
+        log `cat $TLOG`
+        rm -f $TLOG > /dev/null 2> /dev/null
         exit 1
     fi
+    rm -f $TLOG > /dev/null 2> /dev/null
+}
+
+import_registry_configuration()
+{
+    exec_log_exit \
+        "/opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg"
 }
 
 import_registry_configurations()
@@ -32,53 +55,34 @@ import_registry_configurations()
     import_registry_configuration pstore
 }
 
+switch_to_open_provider()
+{
+    /opt/likewise/bin/lwregshell \
+    'set_value' \
+    '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' \
+    'Path' \
+    '/opt/likewise/lib64/liblsass_auth_provider_ad_open.so'
+ }
+
 postinstall()
 {
-    log "LikewiseOpen postinstall begins"
+    log "Package: Likewise Open post-install begins (`date`)"
 
-    /opt/likewise/sbin/lwsmd --start-as-daemon > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "Error: /opt/likewise/sbin/lwsmd --start-as-daemon returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    exec_log_exit "/opt/likewise/sbin/lwsmd --start-as-daemon"
 
     import_registry_configurations
 
-    /etc/init.d/lwsmd stop > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "error: /etc/init.d/lwsmd stop returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    switch_to_open_provider
 
-    /etc/init.d/lwsmd start > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "error: /etc/init.d/lwsmd start returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    exec_log_exit "/etc/init.d/lwsmd stop"
 
-    /opt/likewise/bin/domainjoin-cli query > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "error: /opt/likewise/bin/domainjoin-cli query returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    exec_log_exit "/etc/init.d/lwsmd start"
 
-    pam-auth-update --package > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "error: pam-auth-update --pacakge returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    exec_log_exit "/opt/likewise/bin/domainjoin-cli query"
 
-    log "LikewiseOpen postinstall finished"
+    exec_log_exit "pam-auth-update --package"
+
+    log "Package: Likewise Open post-install finished"
 }
 
 case "$1" in
diff --git a/build/packages/open/deb/likewise-open.preinst b/build/packages/open/deb/likewise-open.preinst
--- a/build/packages/open/deb/likewise-open.preinst
+++ b/build/packages/open/deb/likewise-open.preinst
@@ -1,40 +1,77 @@
 #!/bin/sh
 
-set -e
+LOG=/tmp/LikewiseOpen.log
+TLOG=/tmp/LikewiseOpenTemp.txt
+
+log()
+{
+    echo $1
+    echo $1 >> $LOG
+}
+
+exec_log()
+{
+    $1 > $TLOG
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo $1 >> $LOG
+    else
+        log "Error: $1 returned $err"
+        log `cat $TLOG`
+    fi
+}
+
+exec_log_exit()
+{
+    $1 > $TLOG
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo $1 >> $LOG
+    else
+        log "Error: $1 returned $err"
+        log `cat $TLOG`
+        exit 1
+    fi
+}
 
 case "$1" in
     abort-upgrade)
     ;;
 
     upgrade)
-        pam-auth-update --package
+        exec_log_exit "pam-auth-update --package"
 
         if dpkg --compare-versions "$2" le "4.1.2982-0ubuntu3"; then
             # Shutdown old daemons (if running)
             if [ -f /etc/init.d/likewise-open ]
             then
-                /etc/init.d/likewise-open stop || true
+                exec_log /etc/init.d/likewise-open stop
+            else
+                log "Warning: /etc/init.d/likwise-open is not present."
             fi
 
             save_4_1_files
 
-            pam-auth-update --package --remove likewise-open
+            exec_log_exit "pam-auth-update --package --remove likewise-open"
 
             if [ -x /usr/bin/domainjoin-cli ]; then
-                /usr/bin/domainjoin-cli leave || true
+                exec_log "/usr/bin/domainjoin-cli leave"
+            else
+                log "Warning: /usr/bin/domainjoin-cli is not present."
             fi
         fi
 
         # remove obsolete conffiles from previous versions
         if dpkg --compare-versions "$2" lt-nl "6.0.0"; then
 
-        # from 4.1
-        rm_conffile /etc/samba/lwiauthd.conf
-        rm_conffile /etc/security/pam_lwidentity.conf
-        rm_conffile /etc/default/likewise-open
-        rm_conffile /etc/init.d/likewise-open
-        # from 5.0
-        rm_conffile /etc/init.d/npcmuxd
+            # from 4.1
+            rm_conffile /etc/samba/lwiauthd.conf
+            rm_conffile /etc/security/pam_lwidentity.conf
+            rm_conffile /etc/default/likewise-open
+            rm_conffile /etc/init.d/likewise-open
+
+            # from 5.0
+            rm_conffile /etc/init.d/npcmuxd
         fi
     ;;
 
diff --git a/build/packages/open/deb/likewise-open.prerm b/build/packages/open/deb/likewise-open.prerm
--- a/build/packages/open/deb/likewise-open.prerm
+++ b/build/packages/open/deb/likewise-open.prerm
@@ -1,30 +1,64 @@
-#!/bin/sh -e
+#!/bin/sh
 
-DOMAINJOIN=/usr/bin/domainjoin-cli
-LWSMD=/etc/init.d/lwsmd
+LOG=/tmp/LikewiseOpen.log
+TLOG=/tmp/LikewiseOpenTemp.txt
+
+DOMAINJOIN=/opt/likewise/bin/domainjoin-cli
+
+log()
+{
+    echo $1
+    echo $1 >> $LOG
+}
+
+preuninstall()
+{
+    log "Package: Likewise Open pre-uninstall begins (`date`)"
+
+    pam-auth-update --package --remove likewise-open > $TLOG 2>&1
+    err=$?
+    if [ $err -ne 0 ]; then
+        log "Error: pam-auth-update --package --remove likewise-open returned $err"
+        log `cat $TLOG`
+        exit 1
+    fi
+
+    # Remove references elsewhere.
+    if [ -x $DOMAINJOIN ]
+    then
+        $DOMAINJOIN configure --disable nsswitch  > $TLOG 2>&1
+        echo "$DOMAINJOIN configure --disable nsswitch" >> $LOG
+        cat $TLOG >> $LOG
+
+        $DOMAINJOIN configure --disable ssh > $TLOG 2>&1
+        echo "$DOMAINJOIN configure --disable ssh" >> $LOG
+        cat $TLOG >> $LOG
+
+        $DOMAINJOIN configure --long `hostname --long` \
+                              --short `hostname --short` \
+                              --disable krb5 > $TLOG 2>&1
+        echo "$DOMAINJOIN configure --long `hostname --long` --short `hostname --short` --disable krb5" >> $LOG
+        cat $TLOG >> $LOG
+    else
+        log "Warning: $DOMAINJOIN is missing or not executable"
+    fi
+
+    # Stop all daemons; none should be needed anymore.
+    if [ -x /etc/init.d/lwsmd ]
+    then
+        /etc/init.d/lwsmd stop > $TLOG 2>&1
+        echo "/etc/init.d/lwsmd stop" >> $LOG
+        cat $TLOG >> $LOG
+    else
+        log "Warning: /etc/init.d/lwsmd is missing or not executable"
+    fi
+
+    log "Package: Likewise Open pre-uninstall finished"
+}
 
 case "$1" in
     remove)
-    # Removing this package; no upgrade in progress
-
-        # Remove references in PAM.
-        pam-auth-update --package --remove likewise-open
-
-        # Remove references elsewhere.
-        if [ -x $DOMAINJOIN ]
-        then
-            $DOMAINJOIN configure --disable nsswitch > /dev/null 2>&1
-            $DOMAINJOIN configure --disable ssh > /dev/null 2>&1
-            $DOMAINJOIN configure --long `hostname --long` \
-                                  --short `hostname --short` \
-                                  --disable krb5 > /dev/null 2>&1
-        fi
-
-        # Stop all daemons; none should be needed anymore.
-        if [ -x $LWSMD ]
-        then
-            $LWSMD stop
-        fi
+        preuninstall
     ;;
 
     failed-upgrade)
