New logging for installs, removed attempts to upgrade official Ubuntu packages (it can't work)
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@51964 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/packages/open/deb/likewise-open.postinst b/build/packages/open/deb/likewise-open.postinst
--- a/build/packages/open/deb/likewise-open.postinst
+++ b/build/packages/open/deb/likewise-open.postinst
@@ -1,40 +1,91 @@
 #!/bin/sh
 
+UPGRADEDIR=/opt/likewise-upgrade
+
 LOG=/tmp/LikewiseOpen.log
 TLOG=/tmp/LikewiseOpenTemp.txt
 
+PKG_ARCH="__PKG_ARCH"
+
+# Display to screen and log file with a blank line.
 log()
 {
-    echo $1
-    echo $1 >> $LOG
+    echo $@
+    echo
+    echo $@ >> $LOG
+    echo >> $LOG
 }
 
+_log()
+{
+    echo $@
+    echo $@ >> $LOG
+}
+
+# Display to file.
+logfile()
+{
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file.
 exec_log()
 {
-    $1 > $TLOG
+    $@ > $TLOG 2>&1
     err=$?
     if [ $err -eq 0 ]; then
-        echo $1 >> $LOG
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
     else
-        log "Error: $1 returned $err"
-        log `cat $TLOG`
+        _log "Error: $@ returned $err"
+        _log `cat $TLOG`
+        _log
     fi
-    rm -f $TLOG > /dev/null 2> /dev/null
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
 }
 
-exec_log_exit()
+# Execute command.
+# Log only to file.
+exec_logfile()
 {
-    $1 > $TLOG
+    $@ > $TLOG 2>&1
     err=$?
     if [ $err -eq 0 ]; then
-        echo $1 >> $LOG
+        echo "Success: $@" >> $LOG
     else
-        log "Error: $1 returned $err"
-        log `cat $TLOG`
-        rm -f $TLOG > /dev/null 2> /dev/null
+        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
+    fi
+    cat $TLOG >> $LOG
+    echo >> $LOG
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file and then exit.
+exec_log_exit()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err  (aborting this script)"
+        _log `cat $TLOG`
+        _log
+        rm -f $TLOG > /dev/null 2>&1
         exit 1
     fi
-    rm -f $TLOG > /dev/null 2> /dev/null
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
 }
 
 import_registry_configuration()
@@ -55,22 +106,97 @@ import_registry_configurations()
     import_registry_configuration pstore
 }
 
+import_5_0123_file()
+{
+    CONVERT="/opt/likewise/bin/conf2reg"
+    REGIMPORT="/opt/likewise/bin/lwregshell import"
+
+    COMMAND=$1
+    SOURCE=$2
+    # DEST is not necessary for some commands.
+    DEST=$3
+
+    if [ -f $SOURCE ]; then
+        exec_log $CONVERT $COMMAND $SOURCE $DEST > /dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
+
+        if [ -n "$DEST" -a -f "$DEST" ]; then
+            exec_log $REGIMPORT $DEST > /dev/null 2>&1
+            if [ $? -ne 0 ]; then
+                return 1
+            fi
+        fi
+    fi
+    return 0
+}
+
+restore_5_0123_configuration()
+{
+    CONVERT="/opt/likewise/bin/conf2reg"
+
+    if [ ! -d "${UPGRADEDIR}" ]; then
+        return 0;
+    fi
+
+    import_5_0123_file "--lsass" "${UPGRADEDIR}/lsassd.conf" \
+        "${UPGRADEDIR}/lsassd.conf.reg"
+
+    import_5_0123_file "--netlogon" "${UPGRADEDIR}/netlogon.conf" \
+        "${UPGRADEDIR}/netlogon.conf.reg"
+
+    import_5_0123_file "--eventlog" "${UPGRADEDIR}/eventlogd.conf" \
+        "${UPGRADEDIR}/eventlogd.conf.reg"
+
+    import_5_0123_file "--pstore-sqlite" "${UPGRADEDIR}/pstore.db"
+}
+
+fix_old_registry()
+{
+    DomainSeparator=`/opt/likewise/bin/lwregshell list_values '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' | grep DomainSeparator | sed -e 's/ *[^ ]\+[ ]\+[^ ]\+[ ]\+"\([^ ]*\)"$/\1/'`
+    SpaceReplacement=`/opt/likewise/bin/lwregshell list_values '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' | grep SpaceReplacement | sed -e 's/ *[^ ]\+[ ]\+[^ ]\+[ ]\+"\([^ ]*\)"$/\1/'`
+    if [ -n "${DomainSeparator}" ]; then
+        if [ "$DomainSeparator" = "\\\\" ]; then
+            DomainSeparator="\\"
+        fi
+        /opt/likewise/bin/lwregshell set_value '[HKEY_THIS_MACHINE\Services\lsass\Parameters]' 'DomainSeparator' "$DomainSeparator"
+    fi
+    if [ -n "${SpaceReplacement}" ]; then
+        /opt/likewise/bin/lwregshell set_value '[HKEY_THIS_MACHINE\Services\lsass\Parameters]' 'SpaceReplacement' "$SpaceReplacement"
+    fi
+}
+
 switch_to_open_provider()
 {
-    /opt/likewise/bin/lwregshell \
-    'set_value' \
-    '[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]' \
-    'Path' \
-    '/opt/likewise/lib64/liblsass_auth_provider_ad_open.so'
- }
+    _value='[HKEY_THIS_MACHINE\Services\lsass\Parameters\Providers\ActiveDirectory]'
+    _path=''
+    case "${PKG_ARCH}" in
+      x86_64|amd64)
+        _path='/opt/likewise/lib64/liblsass_auth_provider_ad_open.so'
+        ;;
+      i?86)
+        _path='/opt/likewise/lib/liblsass_auth_provider_ad_open.so'
+        ;;
+      *)
+        _path='error'
+        ;;
+    esac
+
+    exec_log /opt/likewise/bin/lwregshell 'set_value' "$_value" 'Path' "$_path"
+}
 
 postinstall()
 {
     log "Package: Likewise Open post-install begins (`date`)"
 
-    exec_log_exit "/opt/likewise/sbin/lwsmd --start-as-daemon"
+    exec_log_exit "/opt/likewise/sbin/lwsmd --start-as-daemon --disable-autostart"
+
+    restore_5_0123_configuration
 
     import_registry_configurations
+
+    fix_old_registry
 
     switch_to_open_provider
 
