MERGE: -c 61840 /branches/Enterprise-6.1 -> /trunk/Platform
Bug 12559 - [6.1 Polish] Installer - localhost hostname causes Mac installation to fail

Check for a hostname of "localhost" and fail the installation with
a log message, and a popup for GUI installation.


git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@61843 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/package/open/mac/Resources/preflight b/package/open/mac/Resources/preflight
--- a/package/open/mac/Resources/preflight
+++ b/package/open/mac/Resources/preflight
@@ -274,6 +274,23 @@ preserve_6_1_configuration()
 ##
 log "See /var/log/likewise-open-install.log for a complete installation log"
 
+if [ "`uname -n`" = "localhost" ]
+then
+    log "Error: local host name is 'localhost' - please change it before installing Likewise Enterprise."
+
+    if [ ! -t 0 ]
+    then
+        /usr/bin/osascript << EOF
+tell application "System Events"
+    activate
+    display dialog "Error: local host name is 'localhost' - please change it before installing Likewise Enterprise."
+end tell
+EOF
+    fi
+
+    exit 1
+fi
+
 determine_upgrade_type
 
 stop_daemons
