Make things as consistent as I can across platforms.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@52005 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/packages/open-upgrade/pkg/postinstall b/build/packages/open-upgrade/pkg/postinstall
--- a/build/packages/open-upgrade/pkg/postinstall
+++ b/build/packages/open-upgrade/pkg/postinstall
@@ -1,58 +1,108 @@
 #!/bin/sh
 
-DAEMONS_TO_HALT=__LW_DAEMONS_TO_HALT
+DAEMONS_TO_HALT="lwmgmtd lwrdrd npcmuxd likewise-open likewise-winbindd centeris.com-lwiauthd centeris.com-gpagentd lwsmd lwregd netlogond lwiod dcerpcd eventlogd lsassd"
 
 LOG=/tmp/LikewiseOpen.log
 TLOG=/tmp/LikewiseOpenTemp.txt
 
+# Display to screen and log file.
 log()
 {
-    echo $1
-    echo $1 >> $LOG
+    echo $@
+    echo
+    echo $@ >> $LOG
+    echo >> $LOG
 }
 
+_log()
+{
+    echo $@
+    echo $@ >> $LOG
+}
+
+# Display to file.
+logfile()
+{
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file.
 exec_log()
 {
-    $1 > $TLOG
+    $@ > $TLOG 2>&1
     err=$?
     if [ $err -eq 0 ]; then
-        echo $1 >> $LOG
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
     else
-        log "Error: $1 returned $err"
-        log `cat $TLOG`
+        _log "Error: $@ returned $err"
+        _log `cat $TLOG`
+        _log
     fi
-    rm -f $TLOG > /dev/null 2> /dev/null
+    rm -f $TLOG > /dev/null 2>&1
 }
 
-exec_log_exit()
+# Execute command.
+# Log only to file.
+exec_logfile()
 {
-    $1 > $TLOG
+    $@ > $TLOG 2>&1
     err=$?
     if [ $err -eq 0 ]; then
-        echo $1 >> $LOG
+        echo "Success: $@" >> $LOG
     else
-        log "Error: $1 returned $err"
-        log `cat $TLOG`
-        rm -f $TLOG > /dev/null 2> /dev/null
+        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
+    fi
+    cat $TLOG >> $LOG
+    echo >> $LOG
+    rm -f $TLOG > /dev/null 2>&1
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file and then exit.
+exec_log_exit()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err  (aborting this script)"
+        _log `cat $TLOG`
+        _log
+        rm -f $TLOG > /dev/null 2>&1
         exit 1
     fi
-    rm -f $TLOG > /dev/null 2> /dev/null
+    rm -f $TLOG > /dev/null 2>&1
 }
 
 determine_upgrade_type()
 {
     VERSIONFILE=/opt/likewise/data/VERSION
     if [ -f $VERSIONFILE ]; then
-        UPGRADING=1
         UPGRADEDIR=/opt/likewise-upgrade
-        mkdir -p "${UPGRADEDIR}"
+        exec_log_exit mkdir -p "${UPGRADEDIR}"
 
-        if [ -n "`grep '^VERSION=5.0' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.1' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.2' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.3' $VERSIONFILE`" ]; then
+        exec_log_exit cat $VERSIONFILE
+        if [ -n "`grep '^VERSION=5.0' $VERSIONFILE`" ]; then
             UPGRADING_FROM_5_0123=1
-            log "Preserving 5.x (0 <= x <= 3) configuration in ${UPGRADEDIR}."
+            log "Preserving 5.0 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.1' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.1 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.2' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.2 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.3' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.3 configuration in ${UPGRADEDIR}."
         elif [ -n "`grep '^VERSION=5.4' $VERSIONFILE`" ]; then
             UPGRADING_FROM_5_4=1
             log "Preserving 5.4 configuration in ${UPGRADEDIR}."
@@ -64,20 +114,20 @@ preserve_5_0123_configuration()
 {
     if [ -n "${UPGRADING_FROM_5_0123}" ]; then
         if [ -f "/etc/likewise/eventlogd.conf" ]; then
-            cp "/etc/likewise/eventlogd.conf" "${UPGRADEDIR}"
+            exec_log_exit cp "/etc/likewise/eventlogd.conf" "${UPGRADEDIR}"
         fi
 
         if [ -f "/etc/likewise/lsassd.conf" ]; then
-            cp "/etc/likewise/lsassd.conf" "${UPGRADEDIR}"
+            exec_log_exit cp "/etc/likewise/lsassd.conf" "${UPGRADEDIR}"
         fi
 
         if [ -f "/etc/likewise/netlogon.conf" ]; then
-            cp "/etc/likewise/netlogon.conf" "${UPGRADEDIR}"
+            exec_log_exit cp "/etc/likewise/netlogon.conf" "${UPGRADEDIR}"
         fi
 
         if [ -f "/var/lib/likewise/db/pstore.db" ]; then
-            cp "/var/lib/likewise/db/pstore.db" "${UPGRADEDIR}"
-            chmod 700 "${UPGRADEDIR}/pstore.db"
+            exec_log_exit cp "/var/lib/likewise/db/pstore.db" "${UPGRADEDIR}"
+            exec_log_exit chmod 700 "${UPGRADEDIR}/pstore.db"
         fi
     fi
 }
@@ -88,7 +138,7 @@ preserve_5_4_configuration()
         for file in dcerpcd.reg eventlogd.reg lsassd.reg lwiod.reg lwreg.reg netlogond.reg pstore.reg
         do
             if [ -f "/etc/likewise/${file}" ]; then
-                cp "/etc/likewise/${file}" "${UPGRADEDIR}"
+                exec_log_exit cp "/etc/likewise/${file}" "${UPGRADEDIR}"
             fi
         done
     fi
@@ -96,7 +146,7 @@ preserve_5_4_configuration()
 
 postinstall()
 {
-    log "Package: Likewise Open Upgrade Helper begins (`date`)"
+    log "Package: Likewise Open Upgrade begins (`date`)"
 
     # Stop any Likewise daemon (process capture for debugging).
     exec_log "ps -ef"
@@ -115,7 +165,7 @@ postinstall()
 
     preserve_5_4_configuration
 
-    log "Package: Likewise Open Upgrade Helper finished"
+    log "Package: Likewise Open Upgrade finished"
 }
 
 postinstall
