Fix error recovery when import fails due to a parse error.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@59876 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/lwreg/server/lwregd/lwreg-backend.in b/lwreg/server/lwregd/lwreg-backend.in
--- a/lwreg/server/lwregd/lwreg-backend.in
+++ b/lwreg/server/lwregd/lwreg-backend.in
@@ -118,7 +118,7 @@ select_backend()
 
   echo "Importing registry..."
   import_registry $TMPEXPORT
-  if [ $? -eq 1 ]; then
+  if [ $? -ne 0 ]; then
     #
     # Restore current backend if import fails, and restart services
     #
@@ -126,7 +126,12 @@ select_backend()
     switch_backend $CUR_BACKEND
     $ETC_INIT_DIR/lwsmd start > /dev/null
     $BIN_DIR/lwsm start lsass > /dev/null
-    usage "Failed to import registry into backend: $backend"
+    echo
+    echo "Failed to import registry into backend: $backend"
+    echo "Restoring $CUR_BACKEND registry backend."
+    echo
+    echo "Look for syntax errors in file $TMPEXPORT."
+    exit 1
   fi
   echo "Done."
   rm -f $TMPEXPORT
@@ -169,8 +174,8 @@ main()
         shift
     esac
   done
+  CUR_BACKEND=`current_backend`
   if [ -z "$backend" ]; then
-    CUR_BACKEND=`current_backend`
     echo "Current backend: $CUR_BACKEND"
     exit 0
   fi
