Fix for bug 11963 - LWISE: Domain join fails with an error "Error: LW_ERROR_NOT_HANDLED [code 0x00009c51]" for all MAC machines.
Problem was due to new lsass-import.reg files not being processed on product install for the Mac.


git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@53922 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/products/lwiso/macpckgr/Resources/postflight b/build/products/lwiso/macpckgr/Resources/postflight
--- a/build/products/lwiso/macpckgr/Resources/postflight
+++ b/build/products/lwiso/macpckgr/Resources/postflight
@@ -350,9 +350,26 @@ restore_6_0_configuration()
 import_registry()
 {
     REGFILES="lwreg.reg netlogond.reg eventlogd.reg lsassd.reg lwiod.reg dcerpcd.reg pstore.reg"
-    REGIMPORT="/opt/likewise/bin/lwregshell upgrade"
+    REGFILES_IMPORT="lsassd-import.reg"
+    REGUPGRADE="/opt/likewise/bin/lwregshell upgrade"
+    REGIMPORT="/opt/likewise/bin/lwregshell import"
 
     for regfile in ${REGFILES}
+    do
+        FILEPATH="/opt/likewise/share/config/${regfile}"
+        if [ -f ${FILEPATH} ]
+        then
+            echo "Upgrading registry settings from (${FILEPATH})"
+            ${REGUPGRADE} ${FILEPATH} > /dev/null 2>&1
+            exitcode=$?
+
+            if [ $exitcode -ne '0' ]
+            then
+                echo "There was an error importing ${FILEPATH} into the registry."
+            fi
+        fi
+    done
+    for regfile in ${REGFILES_IMPORT}
     do
         FILEPATH="/opt/likewise/share/config/${regfile}"
         if [ -f ${FILEPATH} ]
