Some Mac installer changes from Platform-6.1
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@57968 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/products/lwiso/macpckgr/Resources/preflight b/build/products/lwiso/macpckgr/Resources/preflight
--- a/build/products/lwiso/macpckgr/Resources/preflight
+++ b/build/products/lwiso/macpckgr/Resources/preflight
@@ -1,30 +1,93 @@
 #!/bin/bash
 
-log_info()
+UPGRADEDIR=/opt/likewise-upgrade
+# PKG_ARCH="__PKG_ARCH"
+
+LOG=/var/log/likewise-open-install.log
+TLOG=/tmp/LikewiseOpenTemp.txt
+
+DAEMONS_TO_KILL="lwmgmtd lwrdrd npcmuxd likewise-open centeris.com-lwiauthd lwsmd lwregd netlogond lwiod dcerpcd eventlogd lsassd srvsvcd"
+
+# Display to screen and log file with a blank line between entires.
+log()
 {
-    echo "$@" 1>&2
+    echo $@
+    echo
+    echo $@ >> $LOG
+    echo >> $LOG
 }
 
-stop_and_disable_old_daemon()
+# Display to screen and log file with no blank line.
+_log()
 {
-    SERVICE=$1
-    SERVICE_PATH=/opt/likewise/sbin/$SERVICE
-    SERVICE_NAME=com.likewisesoftware.$SERVICE
-    SERVICE_DAEMON_OLD=/System/Library/LaunchDaemons/$SERVICE_NAME.plist
+    echo $@
+    echo $@ >> $LOG
+}
 
-    if [ -f $SERVICE_DAEMON_OLD ]; then
-        launchctl list | grep $SERVICE_NAME > /dev/null
-        if [ $? -eq 0 ]; then
-            log_info "Stopping Likewise $SERVICE service"
-            launchctl stop $SERVICE_NAME > /dev/null
-        fi
-        log_info "Disable Likewise $SERVICE service"
-        launchctl unload $SERVICE_DAEMON_OLD > /dev/null
-        rm $SERVICE_DAEMON > /dev/null
-        if [ -f $SERVICE_PATH ]; then
-            rm $SERVICE_PATH > /dev/null
-        fi
+# Display to file.
+logfile()
+{
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file.
+run()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err"
+        _log `cat $TLOG`
+        _log
     fi
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
+
+# Execute command.
+# Log only to file.
+run_quiet()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+    else
+        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
+    fi
+    cat $TLOG >> $LOG
+    echo >> $LOG
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file and then exit.
+run_or_fail()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err  (aborting this script)"
+        _log `cat $TLOG`
+        _log
+        rm -f $TLOG > /dev/null 2>&1
+        exit 1
+    fi
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
 }
 
 stop_and_disable_daemon()
@@ -32,114 +95,96 @@ stop_and_disable_daemon()
     SERVICE=$1
     SERVICE_PATH=/opt/likewise/sbin/$SERVICE
     SERVICE_NAME=com.likewisesoftware.$SERVICE
+    SERVICE_DAEMON_OLD=/System/Library/LaunchDaemons/$SERVICE_NAME.plist
     SERVICE_DAEMON=/Library/LaunchDaemons/$SERVICE_NAME.plist
 
+    if [ -f $SERVICE_DAEMON_OLD ]; then
+        SERVICE_DAEMON=$SERVICE_DAEMON_OLD
+    fi
+
     if [ -f $SERVICE_DAEMON ]; then
+
         launchctl list | grep $SERVICE_NAME > /dev/null
         if [ $? -eq 0 ]; then
-            log_info "Stopping Likewise $SERVICE service"
-            launchctl stop $SERVICE_NAME > /dev/null
+#            log "Stopping Likewise $SERVICE service"
+            run_quiet "launchctl stop $SERVICE_NAME"
         fi
-        log_info "Disable Likewise $SERVICE service"
-        launchctl unload $SERVICE_DAEMON > /dev/null
-        rm $SERVICE_DAEMON > /dev/null
+
+#        log "Disable Likewise $SERVICE service"
+        run_quiet "launchctl unload $SERVICE_DAEMON"
+        run_quiet "rm $SERVICE_DAEMON"
         if [ -f $SERVICE_PATH ]; then
-            rm $SERVICE_PATH > /dev/null
+            run_quiet "rm $SERVICE_PATH"
         fi
     fi
 }
 
-save_daemon()
+stop_daemons()
 {
-    SERVICE=$1
-    SERVICE_PATH=/opt/likewise/sbin/$(SERVICE)d
-    SERVICE_NAME=com.likewisesoftware.$(SERVICE)d
-    SERVICE_DAEMON=/Library/LaunchDaemons/$SERVICE_NAME.plist
+    for daemon in $DAEMONS_TO_KILL; do
+        stop_and_disable_daemon $daemon
+    done
 
-    if [ -f $SERVICE_DAEMON ]; then
-        launchctl list | grep $SERVICE_NAME > /dev/null
-        if [ $? -eq 0 ]; then
-            log_info "Saving running status of Likewise $SERVICE service"
-            touch /tmp/$SERVICE.restart
-        fi
-    fi
-}
-
-stop_obsolete_daemons()
-{
-    stop_and_disable_old_daemon npcmuxd
-    stop_and_disable_daemon npcmuxd
-    stop_and_disable_daemon lwrdrd
-    stop_and_disable_daemon lsmbd
-    stop_and_disable_old_daemon dcerpcd
-    stop_and_disable_daemon lwmgmtd
-    stop_and_disable_old_daemon netlogond
-
-    log_info "All obsolete Likewise services now stopped and disabled"
-}
-
-save_daemons()
-{
-    save_daemon lsass
-    save_daemon netlogon
-    save_daemon eventlog
-    save_daemon lwio
-    save_daemon dcerpc
-
-    log_info "All Likewise services now have their running status saved"
+#    log "All Likewise services now stopped and disabled"
 }
 
 disable_plugin()
 {
-    PLUGIN_DIR_OPEN=LWIDSPlugin.dsplug
-    PLUGIN_DIR_ENT=LWEDSPlugin.dsplug
-    PLUGIN_DIR=LWDSPlugin.dsplug
-    SRC_DIR=/opt/likewise/lib
     FRAMEWORK_DIR="/System/Library/Frameworks/DirectoryService.framework/Resources/Plugins"
     LIBRARY_DS_DIR="/Library/DirectoryServices/PlugIns"
 
-    log_info "Disable any former Likewise DS plugin links"
-    if [ -h $FRAMEWORK_DIR/$PLUGIN_DIR_OPEN ]; then
-       /bin/rm -f $FRAMEWORK_DIR/$PLUGIN_DIR_OPEN
-    fi
+    for plugin in LWIDSPlugIn LWEDSPlugIn LWDSPlugin ; do
+        path="$FRAMEWORK_DIR/${plugin}.dsplug"
+        if [ -h "${path}" ]; then
+            run_or_fail "rm -fv ${path}"
+        fi
+    done
 
-    if [ -h $FRAMEWORK_DIR/$PLUGIN_DIR_ENT ]; then
-       /bin/rm -f $FRAMEWORK_DIR/$PLUGIN_DIR_ENT
-    fi
-
-    log_info "Disable prior Likewise DS plugin link"
-    if [ -h $FRAMEWORK_DIR/$PLUGIN_DIR ]; then
-       /bin/rm -f $FRAMEWORK_DIR/$PLUGIN_DIR
-    fi
-
-    if [ -h $LIBRARY_DS_DIR/$PLUGIN_DIR ]; then
-       /bin/rm -r $LIBRARY_DS_DIR/$PLUGIN_DIR
-    fi
+    for plugin in LWIDSPlugIn LWEDSPlugIn LWDSPlugin ; do
+        path="$LIBRARY_DS_DIR/${plugin}.dsplug"
+        if [ -d "${path}" ]; then
+            run_or_fail "rm -r ${path}"
+        fi
+    done
 }
 
 determine_upgrade_type()
 {
     VERSIONFILE=/opt/likewise/data/VERSION
+    ENTERPRISE_VERSIONFILE=/opt/likewise/data/ENTERPRISE_VERSION
+
+    if [ -f $ENTERPRISE_VERSIONFILE ]; then
+        log "$ENTERPRISE_VERSIONFILE exists: Uninstall Likewise Enterprise before proceeding."
+        exit 1
+    elif [ -f /opt/likewise/sbin/gpagentd ]; then
+        log "/opt/likewise/sbin/gpagentd exists: Uninstall Likewise Enterprise before proceeding."
+        exit 1
+    fi
+
     if [ -f $VERSIONFILE ]; then
-        log_info "Previous Likewise software installation detected"
-        if [ -n "`grep '^VERSION=5.0' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.1' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.2' $VERSIONFILE`" -o \
-             -n "`grep '^VERSION=5.3' $VERSIONFILE`" ]; then
-            log_info "Upgrade install from 5.0-5.3 version"
+        run_or_fail "mkdir -p ${UPGRADEDIR}"
+        run_or_fail "cp $VERSIONFILE ${UPGRADEDIR}"
+
+        run_or_fail "cat $VERSIONFILE"
+        if [ -n "`grep '^VERSION=5.0' $VERSIONFILE`" ]; then
             UPGRADING_FROM_5_0123=1
-            UPGRADEDIR5=/tmp/lw-upgrade-5
-            mkdir -p "${UPGRADEDIR5}"
-            log_info "Preserving 5.0-5.3  configuration in ${UPGRADEDIR5}."
-        else
-            log_info "Upgrade install from 6.X version"
+            log "Preserving 5.0 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.1' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.1 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.2' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.2 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=5.3' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_5_0123=1
+            log "Preserving 5.3 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=6.0' $VERSIONFILE`" ]; then
             UPGRADING_FROM_6_0=1
-            UPGRADEDIR6=/tmp/lw-upgrade-6
-            mkdir -p "${UPGRADEDIR6}"
-            log_info "Preserving 6.0 configuration in ${UPGRADEDIR6}."
+            log "Preserving 6.0 configuration in ${UPGRADEDIR}."
+        elif [ -n "`grep '^VERSION=6.1' $VERSIONFILE`" ]; then
+            UPGRADING_FROM_6_1=1
+            log "Preserving 6.1 configuration in ${UPGRADEDIR}."
         fi
-    else
-        log_info "Regular install"
     fi
 }
 
@@ -147,20 +192,20 @@ preserve_5_0123_configuration()
 {
     if [ -n "${UPGRADING_FROM_5_0123}" ]; then
         if [ -f "/etc/likewise/eventlogd.conf" ]; then
-            cp "/etc/likewise/eventlogd.conf" "${UPGRADEDIR5}"
+            run_or_fail "cp /etc/likewise/eventlogd.conf ${UPGRADEDIR}"
         fi
 
         if [ -f "/etc/likewise/lsassd.conf" ]; then
-            cp "/etc/likewise/lsassd.conf" "${UPGRADEDIR5}"
+            run_or_fail "cp /etc/likewise/lsassd.conf ${UPGRADEDIR}"
         fi
 
         if [ -f "/etc/likewise/netlogon.conf" ]; then
-            cp "/etc/likewise/netlogon.conf" "${UPGRADEDIR5}"
+            run_or_fail "cp /etc/likewise/netlogon.conf ${UPGRADEDIR}"
         fi
 
         if [ -f "/var/lib/likewise/db/pstore.db" ]; then
-            cp "/var/lib/likewise/db/pstore.db" "${UPGRADEDIR5}"
-            chmod 700 "${UPGRADEDIR5}/pstore.db"
+            run_or_fail "cp /var/lib/likewise/db/pstore.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/pstore.db"
         fi
     fi
 }
@@ -169,40 +214,60 @@ preserve_6_0_configuration()
 {
     if [ -n "${UPGRADING_FROM_6_0}" ]; then
         if [ -f "/var/lib/likewise/db/registry.db" ]; then
-            cp "/var/lib/likewise/db/registry.db" "${UPGRADEDIR6}"
-            chmod 700 "${UPGRADEDIR6}/registry.db"
+            run_or_fail "cp /var/lib/likewise/db/registry.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/registry.db"
         fi
 
         if [ -f "/var/lib/likewise/db/sam.db" ]; then
-            cp "/var/lib/likewise/db/sam.db" "${UPGRADEDIR6}"
-            chmod 700 "${UPGRADEDIR6}/sam.db"
+            run_or_fail "cp /var/lib/likewise/db/sam.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/sam.db"
         fi
 
         if [ -f "/var/lib/likewise/db/lwi_events.db" ]; then
-            cp "/var/lib/likewise/db/lwi_events.db" "${UPGRADEDIR6}"
-            chmod 700 "${UPGRADEDIR6}/lwi_events.db"
+            run_or_fail "cp /var/lib/likewise/db/lwi_events.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/lwi_events.db"
         fi
 
         if [ -f "/var/lib/likewise/db/lsass-adcache.db" ]; then
-            cp "/var/lib/likewise/db/lsass-adcache.db" "${UPGRADEDIR6}"
-            chmod 700 "${UPGRADEDIR6}/lsass-adcache.db"
+            run_or_fail "cp /var/lib/likewise/db/lsass-adcache.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/lsass-adcache.db"
         fi
     fi
 }
 
+preserve_6_1_configuration()
+{
+    if [ -n "${UPGRADING_FROM_6_1}" ]; then
+        if [ -f "/var/lib/likewise/db/registry.db" ]; then
+            run_or_fail "cp /var/lib/likewise/db/registry.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/registry.db"
+        fi
+
+        if [ -f "/var/lib/likewise/db/sam.db" ]; then
+            run_or_fail "cp /var/lib/likewise/db/sam.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/sam.db"
+        fi
+
+        if [ -f "/var/lib/likewise/db/lwi_events.db" ]; then
+            run_or_fail "cp /var/lib/likewise/db/lwi_events.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/lwi_events.db"
+        fi
+
+        if [ -f "/var/lib/likewise/db/lsass-adcache.db" ]; then
+            run_or_fail "cp /var/lib/likewise/db/lsass-adcache.db ${UPGRADEDIR}"
+            run_or_fail "chmod 700 ${UPGRADEDIR}/lsass-adcache.db"
+        fi
+    fi
+}
 
 ##
 ## Main
 ##
+log "See /var/log/likewise-open-install.log for a complete installation log"
 
-log_info "Determining if this is an upgrade for first time installation"
 determine_upgrade_type
 
-log_info "Stop and disable obsolete Likewise services"
-stop_obsolete_daemons
-
-# Save the daemon state
-save_daemons
+stop_daemons
 
 # Disable Likewise DS plugin
 disable_plugin
@@ -210,12 +275,15 @@ disable_plugin
 # Save 5.[0123] configuration files and pstore.
 preserve_5_0123_configuration
 
-# Save 6.X configuration files and pstore.
+# Save 6.0 configuration files and pstore.
 preserve_6_0_configuration
+
+# Save 6.1 configuration files and pstore.
+preserve_6_1_configuration
 
 # Remove previous Likwise installation with macuninstall.sh
 /opt/likewise/bin/macuninstall.sh
 
-log_info "Now going to extract all the Likewise components and install the binaries and configuration files"
+log "Extracting and installing the binaries and configuration files"
 
 
