MERGE: -c 59473 /branches/Platform-6.0 -> /trunk/Platform
Bug 12695 - mac migration tool doesn't leave symlinks, breaking apps like VMware Fusion

When moving a user's home directory, create a symbolic link back to
the old name.


git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@59759 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/config/lw-local-user-migrate.sh.in b/config/lw-local-user-migrate.sh.in
--- a/config/lw-local-user-migrate.sh.in
+++ b/config/lw-local-user-migrate.sh.in
@@ -323,6 +323,13 @@ MigrateProfile()
             echo "Failed to remove the original source homedir"
             rc="0"
         fi
+
+        echo "ln -s $DestHomeDirectory $SourceHomeDirectory"
+        ln -s "$DestHomeDirectory" "$SourceHomeDirectory"
+        if [ $? -ne 0 ]; then
+            echo "Failed to create a symbolic link from the source to the destnation home directory"
+            rc="0"
+        fi
     else
         if [ -d $DestHomeDirectory ]; then
             echo "$DestHomeDirectory exists, continuing migration"
