Run the "bootstrap" script in the source directory if it exists.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@61007 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/mk-bootstrap b/build/mk-bootstrap
--- a/build/mk-bootstrap
+++ b/build/mk-bootstrap
@@ -36,6 +36,9 @@ bootstrap()
         if [ -x autogen.sh ]
         then
             ./autogen.sh || fail "could not run autogen.sh in $dir"
+        elif [ -x bootstrap ]
+        then
+            ./bootstrap || fail "could not run bootstrap in $dir"
         else
             autoreconf -fi || fail "could not run autoreconf in $dir"
         fi
