Make mac .dmg files out of a tarball that contains the template files, rather than keeping a huge template .dmg file in the svn tree.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@54749 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/mkdmg b/build/mkdmg
--- a/build/mkdmg
+++ b/build/mkdmg
@@ -37,6 +37,23 @@ exit_on_error $?
 source ${BUILD_ROOT}/src/linux/build/lib/dep-helper.sh
 exit_on_error $?
 
+# Clean up a partial build.
+function cleanup
+{
+    status=$?
+
+    if [ "${BUILD_DMG_TMP_DIR}" ]; then
+        rm -rf "${BUILD_DMG_TMP_DIR}"
+    fi
+
+    if [ $status -ne 0 ]; then
+        warn "Exiting on error $status"
+    fi
+
+    trap EXIT
+    exit $status
+}
+
 function usage
 {
     local _products=`product_list`
@@ -53,7 +70,7 @@ function usage
 
 function main
 {
-    set_ctrlc_trap
+    trap "cleanup" EXIT HUP INT QUIT TERM
 
     parseOptDone=""
     while [ -z "$parseOptDone" ]; do
@@ -98,7 +115,7 @@ function main
         PRODUCT_FULL_RELEASE="${MAIN_RELEASE}.${SVN_REVISION}"
         PRODUCT_DIR="${BUILD_ROOT}/src/linux/build/products/${PRODUCT}/macpckgr"
         PRODUCT_DMG_TEMPLATE_DIR="${BUILD_ROOT}/src/linux/build/products/${PRODUCT}/macdmg"
-        PRODUCT_DMG_TEMPLATE="${BUILD_ROOT}/src/linux/build/products/${PRODUCT}/macdmg/template.dmg"
+        PRODUCT_DMG_TEMPLATE="${PRODUCT_DMG_TEMPLATE_DIR}/template.tar.bz2"
 
         if [ -n "${OFFICIAL_BUILD_NUMBER}" ] ; then
             PRODUCT_FULL_RELEASE="${PRODUCT_FULL_RELEASE}.${OFFICIAL_BUILD_NUMBER}"
@@ -117,9 +134,7 @@ function main
         NAME_MPKG="${PRODUCT_NAME}-${PRODUCT_FULL_VERSION}-${ARCH_RENAME}.mpkg"
         OUT_MPKG="${PRODUCT_BUILD_DIR}/${NAME_MPKG}"
         OUT_DMG="${OUT_DIR}/${PRODUCT_NAME}-${PRODUCT_FULL_VERSION}-${ARCH_RENAME}.dmg"
-        OUT_DMG_TMP="${OUT_DIR}/${PRODUCT_NAME}-${PRODUCT_FULL_VERSION}-${ARCH_RENAME}-tmp.dmg"
-        OUT_DMG_SPEC="${OUT_DIR}/${PRODUCT_NAME}-*-${ARCH_RENAME}.dmg"
-        OUT_DMG_TMP_SPEC="${OUT_DIR}/${PRODUCT_NAME}-*-${ARCH_RENAME}-tmp.dmg"
+        BUILD_DMG_TMP_DIR="${PRODUCT_BUILD_DIR}/dmg.tmp"
 
         # Recreate product build directory
         [ -d "${PRODUCT_BUILD_DIR}" ] && rm -rf "${PRODUCT_BUILD_DIR}"
@@ -132,10 +147,6 @@ function main
             rsync -a "${BUILD_DIST_OS_ROOT}/packages/${PACKAGE}/mac/likewise-${PACKAGE}-${PRODUCT_VERSION}.${PRODUCT_FULL_RELEASE}.${ARCH_RENAME}.pkg" "${PRODUCT_BUILD_DIR_FSROOT}/."
             exit_on_error $?
         done
-
-        # Remove old DMG files
-        rm -f ${OUT_DMG_SPEC}
-        rm -f ${OUT_DMG_TMP_SPEC}
 
         # Prepare package maker files
         rsync -a "${PRODUCT_DIR}/" "${PRODUCT_BUILD_DIR_PMAKER}/"
@@ -162,35 +173,33 @@ function main
             exit $?
         fi
 
-        echo "Template dir path: $PRODUCT_DMG_TEMPLATE_DIR"
-        if [ -d "$PRODUCT_DMG_TEMPLATE_DIR" ]; then
-            echo "Building DMG with template disk image ($PRODUCT_DMG_TEMPLATE)"
-            ditto "${PRODUCT_DMG_TEMPLATE}" "${OUT_DMG_TMP}"
+        echo "Template dir path: ${PRODUCT_DMG_TEMPLATE_DIR}"
+        if [ -d "${PRODUCT_DMG_TEMPLATE_DIR}" ]; then
+            echo "Building DMG from template ${PRODUCT_DMG_TEMPLATE}"
+            # Detach any disk image left over from before.  Ignore errors.
+            if [ -d "${BUILD_DMG_TMP_DIR}" ]; then
+                echo "Remove leftover temporary files"
+                rm -rf "${BUILD_DMG_TMP_DIR}"
+            fi
+            mkdir "${BUILD_DMG_TMP_DIR}"
             exit_on_error $?
-            hdiutil attach "${OUT_DMG_TMP}" > /tmp/build_mount
+            echo "Copy the template"
+            tar -C "${BUILD_DMG_TMP_DIR}" -xjf "${PRODUCT_DMG_TEMPLATE}"
             exit_on_error $?
-            DMG_DEVICE=`cat /tmp/build_mount | grep "${PRODUCT_NAME}" | awk '{print $1;}'`
-            rm /tmp/build_mount
-            echo "Mounted with device: $DMG_DEVICE"
-            ditto "${OUT_MPKG}" "/Volumes/${PRODUCT_NAME}/Installer/$NAME_MPKG"
+            echo "Copy the installer package"
+            ditto "${OUT_MPKG}" "${BUILD_DMG_TMP_DIR}/Installer/${NAME_MPKG}"
             exit_on_error $?
-            sync
-            sync
             echo "Set read only"
-            chmod -Rf go-w /Volumes/${PRODUCT_NAME}
+            chmod -Rf go-w "${BUILD_DMG_TMP_DIR}"
             exit_on_error $?
-            sync
-            sync
-            echo "Detach the DMG"
-            hdiutil detach "${DMG_DEVICE}"
+            echo "Create the DMG"
+            rm -f "${OUT_DMG}"
+            hdiutil create -fs HFS+ -srcfolder "${BUILD_DMG_TMP_DIR}" \
+                -format UDZO -imagekey zlib-level=9 \
+                -volname "${PRODUCT_NAME}" -o "${OUT_DMG}"
             exit_on_error $?
-            sync
-            sync
-            sleep 2
-            echo "Compress the DMG"
-            hdiutil convert ${OUT_DMG_TMP} -format UDZO -imagekey zlib-level=9 -o ${OUT_DMG}
-            exit_on_error $?
-            rm -r ${OUT_DMG_TMP}
+            echo "Remove temporary files"
+            rm -rf "${BUILD_DMG_TMP_DIR}"
         else
             hdiutil create -fs HFS+ -srcfolder "${OUT_MPKG}" "${OUT_DMG}"
             exit_on_error $?
