If there is a post*, then have a pre*; otherwise freebsd will use whatever you have for both.
git-svn-id: svn+ssh://source-control.beyondtrust.com/sources/repo/bt-dev/trunk/Platform/src/linux@50212 9fc1c11e-11b2-4e14-94d8-6c5e05775969

diff --git a/build/packages/open/freebsd/postinstall b/build/packages/open/freebsd/postinstall
--- a/build/packages/open/freebsd/postinstall
+++ b/build/packages/open/freebsd/postinstall
@@ -3,21 +3,89 @@
 LOG=/tmp/LikewiseOpen.log
 TLOG=/tmp/LikewiseOpenTemp.txt
 
+# Display to screen and log file with a blank line between entires.
 log()
 {
-    echo $1
-    echo $1 >> $LOG
+    echo $@
+    echo
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Display to screen and log file.
+_log()
+{
+    echo $@
+    echo $@ >> $LOG
+}
+
+# Display to file.
+logfile()
+{
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file.
+exec_log()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err"
+        _log `cat $TLOG`
+        _log
+    fi
+    rm -f $TLOG > /dev/null 2>&1
+}
+
+# Execute command.
+# Log only to file.
+exec_logfile()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+    else
+        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
+    fi
+    cat $TLOG >> $LOG
+    echo >> $LOG
+    rm -f $TLOG > /dev/null 2>&1
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file and then exit.
+exec_log_exit()
+{
+    $@ > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err  (aborting this script)"
+        _log `cat $TLOG`
+        _log
+        rm -f $TLOG > /dev/null 2>&1
+        exit 1
+    fi
+    rm -f $TLOG > /dev/null 2>&1
 }
 
 import_registry_configuration()
 {
-    /opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg > $TLOG 2>&1
-    err=$?
-    if [ $err -ne 0 ]; then
-        log "Error: /opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg returned $err"
-        log `cat $TLOG`
-        exit 1
-    fi
+    exec_log_exit \
+        "/opt/likewise/bin/lwregshell upgrade /opt/likewise/share/config/$1.reg"
 }
 
 import_registry_configurations()
@@ -32,40 +100,21 @@ import_registry_configurations()
     import_registry_configuration pstore
 }
 
-log "LikewiseOpen postinstall begins"
+postinstall()
+{
+    log "Package: Likewise Open post-install begins (`date`)"
 
-/opt/likewise/sbin/lwsmd --start-as-daemon > $TLOG 2>&1
-err=$?
-if [ $err -ne 0 ]; then
-    log "Error: /opt/likewise/sbin/lwsmd --start-as-daemon returned $err"
-    log `cat $TLOG`
-    exit 1
-fi
+    exec_log_exit "/opt/likewise/sbin/lwsmd --start-as-daemon"
 
-import_registry_configurations
+    import_registry_configurations
 
-/etc/rc.d/lwsmd stop > $TLOG 2>&1
-err=$?
-if [ $err -ne 0 ]; then
-    log "error: /etc/rc.d/lwsmd stop returned $err"
-    log `cat $TLOG`
-    exit 1
-fi
+    exec_log_exit "/etc/rc.d/lwsmd stop"
 
-/etc/rc.d/lwsmd start > $TLOG 2>&1
-err=$?
-if [ $err -ne 0 ]; then
-    log "error: /etc/rc.d/lwsmd start returned $err"
-    log `cat $TLOG`
-    exit 1
-fi
+    exec_log_exit "/etc/rc.d/lwsmd start"
 
-/opt/likewise/bin/domainjoin-cli query > $TLOG 2>&1
-err=$?
-if [ $err -ne 0 ]; then
-    log "error: /opt/likewise/bin/domainjoin-cli query returned $err"
-    log `cat $TLOG`
-    exit 1
-fi
+    exec_log_exit "/opt/likewise/bin/domainjoin-cli query"
 
-log "LikewiseOpen postinstall finished"
+    log "Package: Likewise Open post-install finished"
+}
+
+postinstall
