git-build:package:open:deb Sync up with standard build
(git-build: r61200)

diff --git a/git-build/package/open/deb/likewise-open.postrm.in b/git-build/package/open/deb/likewise-open.postrm.in
--- a/git-build/package/open/deb/likewise-open.postrm.in
+++ b/git-build/package/open/deb/likewise-open.postrm.in
@@ -1,11 +1,131 @@
 #!/bin/sh
 
-set -e
+UPGRADEDIR=/var/lib/likewise-upgrade
+
+LOG=/var/log/likewise-open-install.log
+TLOG=/tmp/LikewiseOpenTemp.txt
+
+PKG_ARCH="@MK_HOST_ARCH@"
+
+DAEMONS_TO_HALT="lwsmd lwregd netlogond lwiod dcerpcd eventlogd lsassd srvsvcd"
+
+# Display to screen and log file with a blank line between entries.
+log()
+{
+    echo $@
+    echo
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Display to screen and log file with no blank line.
+_log()
+{
+    echo $@
+    echo $@ >> $LOG
+}
+
+# Display to file.
+logfile()
+{
+    echo $@ >> $LOG
+    echo >> $LOG
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file.
+run()
+{
+    "$@" > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err"
+        _log `cat $TLOG`
+        _log
+    fi
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
+
+# Execute command.
+# Log only to file.
+run_quiet()
+{
+    "$@" > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+    else
+        echo "Error: $@ returned $err  (ignoring and continuing)" >> $LOG
+    fi
+    cat $TLOG >> $LOG
+    echo >> $LOG
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
+
+# Execute command.
+# If successful, note in log file.
+# If not successful, note on screen and log file and then exit.
+run_or_fail()
+{
+    "$@" > $TLOG 2>&1
+    err=$?
+    if [ $err -eq 0 ]; then
+        echo "Success: $@" >> $LOG
+        cat $TLOG >> $LOG
+        echo >> $LOG
+    else
+        _log "Error: $@ returned $err  (aborting this script)"
+        _log `cat $TLOG`
+        _log
+        rm -f $TLOG > /dev/null 2>&1
+        exit 1
+    fi
+    rm -f $TLOG > /dev/null 2>&1
+    return $err
+}
 
 case "$1" in
+    remove)
+        log "Package: Likewise Open postremove [remove] begins (`date`)"
+
+        run_quiet /usr/sbin/service likewise stop
+        run_quiet /usr/sbin/service lwsmd stop
+
+        for daemon in $DAEMONS_TO_HALT
+        do
+            run_quiet pkill -KILL -x $daemon
+        done
+
+        run_quiet /usr/sbin/update-rc.d likewise remove
+        run_quiet /usr/sbin/update-rc.d lwsmd remove
+
+        log "Package: Likewise Open postremove [remove] finished"
+    ;;
+
     purge)
-        rm -rf /var/lib/likewise
-        rm -rf /etc/likewise
+        log "Package: Likewise Open postremove [purge] begins (`date`)"
+
+        run_quiet /usr/sbin/service likewise stop
+        run_quiet /usr/sbin/service lwsmd stop
+
+        for daemon in $DAEMONS_TO_HALT
+        do
+            run_quiet pkill -KILL -x $daemon
+        done
+
+        run_quiet /usr/sbin/update-rc.d likewise remove
+        run_quiet /usr/sbin/update-rc.d lwsmd remove
+
+        run_quiet rm -rf /var/lib/likewise
+
+        log "Package: Likewise Open postremove [purge] finished"
     ;;
 esac
 
